### ISSUE TITLE
Email log file not written as expected

### ISSUE THREAD

**Issue by phommata** [albertoalcolea/django-emaillog-backend#1]
I have created a signup that sends an email verification and not seeing an email log file. Do I need to do some other steps here?

I have followed the basic steps below.
```
pip install django-emaillog-backend
EMAIL_BACKEND = 'django_emaillog_backend.backends.LoggerBackend'
EMAIL_LOGGER_NAME = 'email_logger'
```

**Comment by albertoalcolea** [comment]
If you specify a logger name with `EMAIL_LOGGER_NAME`, then you need to configure that logger as any other Django/Python logger:
* [https://docs.djangoproject.com/en/4.0/topics/logging/](https://docs.djangoproject.com/en/4.0/topics/logging/)
* [https://docs.python.org/3/library/logging.config.html](https://docs.python.org/3/library/logging.config.html)

For example, if you put this configuration in the `settings.py`, the log messages with the emails will be stored in the file configured in the file handler:

```python
LOGGING = {
	'version': 1,
	'disable_existing_loggers': False,
	'formatters': {
		'verbose': {
			'format' : "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
		},
	},
	'handlers': {
		'file': {
			'level': 'DEBUG',
			'class': 'logging.FileHandler',
			'filename': '/your/working/dir/django_debug.log',
			'formatter': 'verbose',
		},
	},
	'loggers': {
		'email_logger': {
			'handlers': ['file'],
			'propagate': True,
			'level': 'DEBUG',
		},
	}
}

EMAIL_BACKEND = 'django_emaillog_backend.backends.LoggerBackend'

EMAIL_LOGGER_NAME = 'email_logger'
```

Take into account that if you do not specify any `EMAIL_LOGGER_NAME` the lib will use the default Django logger called `django` which, by default, prints the log messages in the console.
